telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000025528C7A088>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset')': /bot1080732833:AAG1esS_Jc3SvaWBObGx7xaUegKWRSppHMw/getMe
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000025528C7A6C8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset')': /bot1080732833:AAG1esS_Jc3SvaWBObGx7xaUegKWRSppHMw/getMe
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000025528C7A848>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset')': /bot1080732833:AAG1esS_Jc3SvaWBObGx7xaUegKWRSppHMw/getMe
